spring.application.name=kaushalsetu-javabackend

spring.datasource.url=jdbc:mysql://localhost:3306/kaushalsetudb20th?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=xxxxxxx
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.main.allow-bean-definition-overriding=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=noreply.kaushalsetu@gmail.com
spring.mail.password=xxxx xxxx xxxx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


server.port=8080
jwt.secret.key=b11fddfcfd20b4409a63cecd3ee19dc1a9a7405096007c286f7c48e087584a6
##JWT exp time in  msec
jwt.expiration=7200000000000000
logging.level.org.springframework.security=debug
# src/main/resources/application.properties
razorpay.key.id=xxxxxxxxxxxxxxxxxxxxxx
razorpay.key.secret=xxxxxxxxxxxxxxxxxxx
# Auto-seed initial data (roles)
spring.sql.init.mode=always
